name: Pacman Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: vansh77-glitch
